//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListingBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listings
    {
        public int ID { get; set; }
        public string ListingName { get; set; }
        public string ListingDescription { get; set; }
        public decimal ListingCost { get; set; }
        public string ListingPhoto { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public int CityID { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public int ListingTypeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual ListingTypes ListingTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
